services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.8.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.8.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_LOG_RETENTION_HOURS: 120
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10
    depends_on:
      - zookeeper

  event-simulator:
    build:
      context: .
      dockerfile: event-simulator/Dockerfile
    environment:
      - LOAD_LEVEL=low
    volumes:
      - ./event-simulator:/event-simulator
    depends_on:
      kafka:
        condition: service_healthy

  airflow:
    build:
      context: .
      dockerfile: app/airflow/Dockerfile
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW_CONN_SPARK_DEFAULT: 'spark://spark-master:7077'
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
        bash -c "airflow db migrate &&
                airflow standalone"
    volumes:
      - ./app/airflow/dags:/opt/airflow/dags
      - ./app/spark/jobs:/opt/spark/jobs
    depends_on:
      - kafka
      - spark-master

  spark-master:
    build:
      context: .
      dockerfile: app/spark/Dockerfile
    ports:
      - "7077:7077"
      - "8081:8080"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.master.Master
      --host spark-master
    volumes:
      - ./app/spark/jobs:/opt/spark/jobs

  spark-worker:
    build:
      context: .
      dockerfile: app/spark/Dockerfile
    ports:
      - "8082:8081"
    environment:
      POSTGRES_URL: ${POSTGRES_URL}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: >
      /opt/spark/bin/spark-class
      org.apache.spark.deploy.worker.Worker
      spark://spark-master:7077
    volumes:
      - ./app/spark/jobs:/opt/spark/jobs
    depends_on:
      - spark-master


networks:
  default:
    name: data-platform-net
    external: true